import * as E from './engine.js';
const app=document.querySelector('#app'),toast=document.querySelector('#toast'),modal=document.querySelector('#modal');
let state=null,selected=new Set(['lin']),settings=JSON.parse(localStorage.getItem('zgt-settings')||'{"sound":true}');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function beep(f=520){if(!settings.sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.03;o.connect(g);g.connect(a.destination);o.start();setTimeout(()=>{o.stop();a.close()},100)}catch{}}
function toastMsg(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800);beep(660)}
function save(manual=true){if(state&&!state.ended){E.saveGame(state);if(manual)toastMsg('进度已保存')}}
function openModal(html){modal.innerHTML=`<div class="modal-backdrop"><div class="modal-card">${html}</div></div>`;modal.classList.remove('hidden')}
function closeModal(){modal.classList.add('hidden');modal.innerHTML=''}
function newGame(){state=E.createInitialState();selected=new Set(['lin']);localStorage.removeItem('zero-g-theater-save');render();intro()}
function load(){state=E.loadGame();if(!state)return toastMsg('没有可读取的存档');selected=new Set(state.members.slice(0,1).map(m=>m.id));render()}
function intro(){openModal(`<h2>终幕前十日</h2><p class="hint">每天有 4 次行动。训练、维修、工作、休息和排练都会改变成员、资源、设备和最终演出。训练失败也会消耗资源并造成后果。</p><button class="primary" id="go">开始排演</button><p class="hint">推荐录屏路线：第1-2天修供电和升降台并解锁灯光室；第3天团队排练；第4-6天分别练林杳台词、米卡灯光、晴文反应；第7天检修；第8-9天两次团队排练；保留至少1个零件进入终幕。路线不会自动执行。</p>`);$('#go').onclick=()=>{closeModal();save(false)}}
function settingsModal(){openModal(`<h2>设置</h2><label><input id="snd" type="checkbox" ${settings.sound?'checked':''}> 提示音</label><p class="hint">游戏自动保存日期、成员、资源、设备、事件、解锁区域和演出进度。</p><button class="primary" onclick="document.querySelector('#modal').classList.add('hidden')">完成</button>`);$('#snd').onchange=e=>{settings.sound=e.target.checked;localStorage.setItem('zgt-settings',JSON.stringify(settings))}}
function confirmReset(){openModal(`<h2>重新开始</h2><p>会清除当前浏览器存档。</p><div class="grid2"><button class="danger" id="yes">确认清除</button><button onclick="document.querySelector('#modal').classList.add('hidden')">取消</button></div>`);$('#yes').onclick=()=>{E.clearSave();closeModal();newGame()}}
function render(){if(!state)return menu();if(state.ended)return ending();game()}
function menu(){app.innerHTML=`<div class="menu"><div class="menu-card"><div class="orbit"></div><h1>失重剧院：终幕排演</h1><p class="hint">近地轨道旧剧院的十日养成与最终现场演出</p><div class="menu-actions"><button class="primary" onclick="newGame()">开始游戏</button><button onclick="load()">继续游戏</button><button onclick="confirmReset()">重新开始</button><button onclick="settingsModal()">设置</button></div></div></div>`}
const bar=(n,v,warn=false)=>`<div><span>${n} ${Math.round(v)}</span><div class="bar ${warn?'warn':''}"><i style="width:${v}%"></i></div></div>`;
const res=(n,v)=>`<div class="resource"><small>${n}</small><b>${v}</b></div>`;
const nm=id=>state.members.find(m=>m.id===id)?.name||id;
function game(){const r=state.resources;app.innerHTML=`<div class="game"><header class="topbar panel"><b class="titlemark">🎭 失重剧院</b><span class="badge">第 ${state.day}/10 天 · ${phase()}</span><span class="badge">行动 ${state.actions}</span><span class="badge">${state.locations[state.location].name}</span><button onclick="save(true)">保存</button><button onclick="pauseMenu()">暂停</button><button onclick="intro()">说明</button></header>
<aside class="panel"><h2>资源</h2><div class="resources">${res('能源',r.energy)}${res('零件',r.parts)}${res('资金',r.credits)}${res('时间',r.rehearsalTime)}${res('道具',r.props)}${res('期待',r.expectation)}</div><h3>设备</h3><div class="device-list">${Object.entries(state.devices).map(([id,d])=>`<div class="device">${d.name}：${d.status}%${d.damaged?' <b style="color:var(--red)">故障</b>':''}<div class="bar"><i style="width:${d.status}%"></i></div></div>`).join('')}</div></aside>
<section class="main-view">${state.phase==='event'?eventView():state.phase==='performance'?performView():mainView()}</section>
<aside class="panel"><h2>成员</h2><div class="members">${state.members.map(memberCard).join('')}</div><h3>关系</h3><div class="device-list">${Object.entries(state.relationships).map(([k,v])=>`<div class="device">${nm(k.split('-')[0])} ↔ ${nm(k.split('-')[1])}：<b style="color:${v<35?'var(--red)':v>65?'var(--green)':'var(--text)'}">${v}</b></div>`).join('')}</div></aside>
<aside class="panel" style="grid-column:1/-1"><h2>目标与记录</h2><div class="log-list">${goals()}${state.eventLog.slice(0,10).map(e=>`<div class="log-entry ${e.type}">第${e.day}天 ${e.title} <small>${e.choice||e.detail||''}</small></div>`).join('')||'<div class="log-entry">暂无重要事件</div>'}</div></aside></div>`;bind()}
function phase(){return{morning:'晨间安排',event:'突发事件',night:'夜间总结',performance:'最终演出'}[state.phase]||state.phase}
function memberCard(m){return`<div class="member ${selected.has(m.id)?'selected':''} ${m.injured?'injured':''}" data-id="${m.id}"><div class="member-head"><strong>${m.name}</strong><span>${m.role}</span></div><small>${m.trait} · ${m.route||'路线未定'} · 剧情${m.story}/3 ${m.injured?'· 受伤':''}</small><div class="mini-stats">${bar('表演',m.acting)}${bar('节奏',m.rhythm)}${bar('专注',m.focus)}${bar('技术',m.tech)}${bar('反应',m.reaction)}${bar('信任',m.trust)}${bar('疲劳',m.fatigue,true)}${bar('压力',m.stress,true)}</div><small>${m.assignment}</small></div>`}
function mainView(){const l=state.locations[state.location];return`<div class="panel stage-scene"><div><div class="scene-art">${icon()}</div><h2>${l.name}</h2><p class="hint">${desc()}</p><div class="prompt-seq">${objects().map(x=>`<button class="cue" onclick="inspect('${x}')">${x}</button>`).join('')}</div></div></div>
${state.phase==='night'?`<div class="panel event-banner"><h2>夜间总结</h2><p>设备会老化，疲劳会累积。</p><button class="primary" onclick="night()">进入下一天</button></div>`:`<div class="panel"><h2>剧院地图</h2><div class="map-grid">${Object.entries(state.locations).map(([id,x])=>`<button class="map-node ${state.location===id?'active':''}" ${!x.unlocked||x.closed?'disabled':''} onclick="goLoc('${id}')">${x.name}<br><small class="${x.closed?'closed':x.unlocked?'':'locked'}">${x.closed?'安全关闭':x.unlocked?'可进入':'未解锁'}</small></button>`).join('')}</div></div><div class="panel"><h2>今日安排</h2><div class="actions">${Object.entries(E.TRAINING_INFO).map(([id,t])=>`<button onclick="train('${id}')">${t.name}<br><small>${t.energy}能源 / ${t.time}时间</small></button>`).join('')}<button onclick="action('repair')">设备维修</button><button onclick="action('rest')">安排休息</button><button onclick="action('work')">外出工作</button><button onclick="action('shop')">采购物资</button><button class="primary" onclick="trigger()">巡查触发事件</button></div></div>`}<div class="panel"><h2>通讯记录</h2><div class="log-list">${state.log.slice(0,8).map(x=>`<div class="log-entry ${x.kind}"><b>${x.title}</b><br><small>${x.detail}</small></div>`).join('')}</div></div>`}
function icon(){return{stage:'🛰️',backstage:'🎒',rehearsal:'📜',lighting:'💡',repair:'🔧',storage:'📦',audience:'🌌'}[state.location]}
function desc(){return{stage:'团队排练、临场反应和最终演出的核心区域。',backstage:'成员整理装备、接工作，也会发生关系摩擦。',rehearsal:'台词与节奏训练室。',lighting:'根据剧情区域手动切换灯光。',repair:'排查母线、升降台和生命维持设备。',storage:'采购能源、零件、道具和餐包。',audience:'观察接驳船观众，管理期待值。'}[state.location]}
function objects(){return{stage:['升降台','月面仪','直播镜头'],backstage:['通讯终端','工具箱'],rehearsal:['台词屏','节拍环'],lighting:['灯光控制台','散热栅格'],repair:['电路诊断台','安全锁'],storage:['物资终端','零件架'],audience:['观察窗','观众席']}[state.location]}
function goals(){return[['供电保持45%以上',state.devices.power.status>=45],['灯轨和升降台完成检修',state.devices.lights.status>=60&&state.devices.lift.status>=60],['完成两次团队排练',state.stats.rehearsals>=2],['观众期待达到60',state.resources.expectation>=60],['进入最终演出',state.day>=10]].map(([x,ok])=>`<div class="log-entry ${ok?'success':''}">${ok?'✅':'⬜'} ${x}</div>`).join('')}
function bind(){$$('.member').forEach(x=>x.onclick=()=>{const id=x.dataset.id;selected.has(id)?selected.delete(id):selected.add(id);render()})}
window.newGame=newGame;window.load=load;window.confirmReset=confirmReset;window.settingsModal=settingsModal;window.intro=intro;window.save=save;
window.pauseMenu=()=>openModal(`<h2>暂停</h2><div class="grid2"><button class="primary" onclick="document.querySelector('#modal').classList.add('hidden')">继续</button><button onclick="save(true)">保存</button><button onclick="state=null;document.querySelector('#modal').classList.add('hidden');render()">返回主菜单</button><button class="danger" onclick="confirmReset()">重新开始</button></div>`);
window.goLoc=id=>{const r=E.moveLocation(state,id);if(r.ok){beep(430);render()}else toastMsg(r.reason)};
window.night=()=>{E.endDay(state);save(false);render()};
window.inspect=n=>openModal(`<h2>${n}</h2><p>该设备会随训练、维修、突发事件和终幕操作改变状态。低完整度可能造成区域关闭或演出事故。</p><button class="primary" onclick="document.querySelector('#modal').classList.add('hidden')">返回</button>`);
window.train=type=>{const ids=[...selected],check=E.canTrain(state,type,ids);if(!check.ok)return toastMsg(check.reason);if(type==='lines')miniLines(ids);if(type==='rhythm')miniRhythm(ids);if(type==='lighting')miniLight(ids);if(type==='repair')miniCircuit(ids);if(type==='reaction')miniReaction(ids);if(type==='ensemble')miniEnsemble(ids)};
function finish(type,ids,score){const r=E.completeTraining(state,type,ids,score,Math.random);closeModal();save(false);toastMsg(r.ok?(r.success?'训练成功':'训练失败，已产生后果'):'训练异常');render()}
window.action=a=>{const id=[...selected][0];if(!id)return toastMsg('请选择成员');if(a==='work')return work(id);if(a==='shop')return shop();const r=a==='repair'?E.repairAction(state,id,12,true):E.restMember(state,id);r.ok?(save(false),render()):toastMsg(r.reason)};
function work(id){openModal(`<h2>${nm(id)} 的小型工作</h2><div class="grid2"><button onclick="job('${id}','signal')">外部信号检修<small class="hint">资金和能源</small></button><button onclick="job('${id}','cargo')">货舱搬运<small class="hint">零件</small></button><button onclick="job('${id}','promo')">轨道宣传<small class="hint">期待值</small></button></div>`)}window.job=(id,k)=>{const r=E.workJob(state,id,k);closeModal();r.ok?(save(false),render(),toastMsg(r.good?'工作成功':'工作受挫')):toastMsg(r.reason)};
function shop(){openModal(`<h2>储藏间采购</h2><div class="grid2"><button onclick="buy('battery')">能源电池 28资金</button><button onclick="buy('parts')">维修零件 22资金</button><button onclick="buy('props')">磁力道具 35资金</button><button onclick="buy('ration')">营养餐包 18资金</button></div>`)}window.buy=k=>{const r=E.buyItem(state,k);r.ok?(closeModal(),save(false),render()):toastMsg(r.reason)};
window.trigger=()=>{const ev=E.maybeTriggerEvent(state,Math.random);if(!ev)return toastMsg('今天的事件已经处理');beep(220);render()};
function eventView(){const ev=state.activeEvent;return`<div class="panel event-banner"><h2>⚠️ ${ev.title}</h2><p>${ev.text}</p><div class="grid2">${ev.options.map(o=>{const off=o.need&&!o.need(state);return`<button class="choice" ${off?'disabled':''} onclick="eventChoice('${o.id}')"><b>${o.label}</b><small>${off?'条件不足':'会改变成员、资源、设备或延迟影响'}</small></button>`}).join('')}</div></div>`}
window.eventChoice=id=>{const r=E.resolveEvent(state,id);if(!r.ok)return toastMsg(r.reason);save(false);toastMsg(r.detail);render();setTimeout(()=>document.querySelector('#night')?.scrollIntoView({behavior:'smooth',block:'center'}),50)};
function miniLines(ids){const seq=['质问','迟疑','恳求','释然'];let step=0,miss=0;openModal(`<h2>台词训练</h2><p class="hint">按顺序选择：质问 → 迟疑 → 恳求 → 释然</p><div class="prompt-seq" id="seq">${seq.map((x,i)=>`<span class="cue ${i===0?'now':''}">${x}</span>`).join('')}</div><div class="prompt-seq">${seq.map(x=>`<button onclick="lineHit('${x}')">${x}</button>`).join('')}</div>`);window.lineHit=x=>{if(x===seq[step]){$$('#seq .cue')[step].className='cue done';step++;if(step===4)finish('lines',ids,1-miss*.16)}else{miss++;toastMsg('情绪顺序错误')}}}
function miniRhythm(ids){let hits=0,total=0,scale=1.65;openModal(`<h2>节奏训练</h2><div class="minigame"><div class="timing-ring" id="ring"><div class="target-ring"></div><b>踩拍</b></div><button class="primary" onclick="rhythmHit()">踩拍</button><p class="hint">圆环进入虚线区时点击，共三次。</p></div>`);const ring=$('#ring');const t=setInterval(()=>{scale-=.04;ring.style.transform=`scale(${scale})`;if(scale<.82){scale=1.65;total++;if(total>=3){clearInterval(t);finish('rhythm',ids,hits/3)}}},60);window.rhythmHit=()=>{if(scale>.82&&scale<1.12)hits++;total++;scale=1.65;if(total>=3){clearInterval(t);finish('rhythm',ids,hits/3)}}}
function miniLight(ids){const targets=[['左前','冷蓝'],['中央','金白'],['右后','暗红']];let step=0,miss=0;const draw=()=>openModal(`<h2>灯光操作</h2><p>第${step+1}个节点：${targets[step][0]}，选择${targets[step][1]}</p><div class="light-board">${targets.map(x=>`<button onclick="lightHit(${targets.findIndex(t=>t[0]===x[0]&&t[1]===x[1])})">${x[0]}<br><b>${x[1]}</b></button>`).join('')}</div><small>错误 ${miss}</small>`);draw();window.lightHit=i=>{if(i!==step)miss++;step++;step<3?draw():finish('lighting',ids,1-miss*.22)}}
function miniCircuit(ids){const seq=['断电挂牌','查断路点','更换过载保险','复位安全锁'];let step=0,miss=0;const draw=()=>openModal(`<h2>维修排查</h2><p>下一步：<b>${seq[step]}</b></p><div class="prompt-seq">${[...seq].reverse().map(x=>`<button onclick="circuitHit('${x}')">${x}</button>`).join('')}</div><small>错误 ${miss}</small>`);window.circuitHit=x=>{if(x!==seq[step])miss++;step++;step<4?draw():finish('repair',ids,1-miss*.23)};draw()}
function miniReaction(ids){const q=[['道具飘向观众','锁定磁扣','关闭灯光'],['听不见提示','震动地板标记','喊台词'],['气闸误报警','确认生命维持面板','中止演出']];let i=0,score=0;const draw=()=>openModal(`<h2>临场反应 ${i+1}/3</h2><div class="reaction-target"><h3>${q[i][0]}</h3><div class="grid2"><button class="primary" onclick="react(true)">${q[i][1]}</button><button onclick="react(false)">${q[i][2]}</button></div></div>`);window.react=ok=>{if(ok)score++;i++;i<3?draw():finish('reaction',ids,score/3)};draw()}
function miniEnsemble(ids){if(ids.length<2)return toastMsg('团队排练至少选择两人');let n=0,score=0;const html=`<h2>团队排练站位</h2><p class="hint">安排中央独白、左侧设备、右侧接应。林杳适合中央，晴文适合右侧接应。</p><div class="light-board"><button onclick="pos('left','')">左侧设备提示</button><button onclick="pos('center','lin')">中央开场独白</button><button onclick="pos('right','qing')">右侧即兴接应</button></div><div id="order" class="prompt-seq"></div><button class="primary" onclick="ensembleGo()">开始合练</button>`;window.pos=(p,good)=>{const target=$('#order');if(!target)return;const m=ids[n++%ids.length];if(m===good)score++;target.innerHTML+=`<span class="cue done">${nm(m)}@${p}</span>`};window.ensembleGo=()=>{if(!$('#order'))return;if(n<3)return toastMsg('至少安排三个位置');const trust=ids.reduce((a,id)=>a+E.getMember(state,id).trust,0)/ids.length/100;finish('ensemble',ids,Math.min(1,.35+score*.2+trust*.35+n*.02))};openModal(html)}
function performView(){const p=state.performance;if(p.stage==='prep'){setTimeout(setupModal,0);return`<div class="panel stage-scene"><div><div class="scene-art">🎭</div><h2>最终演出准备</h2><p class="hint">请在弹出窗口确认站位、设备、灯光顺序和备用方案。</p></div></div>`}if(p.stage==='cue')return cueView();return''}
function setupModal(){if(!state.performance||state.performance.stage!=='prep')return;const sel=id=>`<select id="${id}">${state.members.map(m=>`<option value="${m.id}">${m.name}</option>`).join('')}</select>`;openModal(`<h2>最终演出方案</h2><div class="grid2"><label>主演 ${sel('lead')}</label><label>替补接应 ${sel('understudy')}</label><label>机械设备 ${sel('engineer')}</label><label>第一灯光 ${sel('firstLight')}</label><label>备用方案<select id="backup"><option value="battery">备用电池保灯光</option><option value="human">演员冷光推进剧情</option><option value="none">不设备用</option></select></label></div><p class="hint">站位关系会产生默契加成；之后四次现场变化不能跳过。</p><button class="primary" onclick="lockSetup()">锁定并开始</button>`);$('#lead').value='lin';$('#understudy').value='qing';$('#engineer').value='gu';$('#firstLight').value='mika'}
window.lockSetup=()=>{const r=E.confirmPerformanceSetup(state,{lead:$('#lead').value,understudy:$('#understudy').value,engineer:$('#engineer').value,firstLight:$('#firstLight').value,backup:$('#backup').value});if(!r.ok)return toastMsg(r.reason);closeModal();save(false);render()};
function cueView(){const cue=E.performanceCueInfo(state);return`<div class="panel event-banner"><h2>${cue.title}</h2><p>${cue.hint}</p><div class="grid2">${cue.options.map(o=>{const off=o.need&&!o.need(state,state.performance);return`<button class="choice" ${off?'disabled':''} onclick="liveChoose('${o.id}')"><b>${o.label}</b><small>${off?'条件不足':'选择后完成三次踩拍操作'}</small></button>`}).join('')}</div></div><div class="panel"><div class="timing-ring" id="live"><div class="target-ring"></div><b>等待选择</b></div></div>`}
window.liveChoose=id=>{let scale=1.6,hits=0,total=0;const ring=$('#live'),beat=ring.querySelector('b');beat.textContent='0/3';const timer=setInterval(()=>{scale-=.045;ring.style.transform=`scale(${scale})`;if(scale<.82){scale=1.6;total++;if(total>=3){clearInterval(timer);liveDone(id,.35+hits*.18)}}},55);ring.onclick=()=>{if(scale>.82&&scale<1.08)hits++;total++;scale=1.6;beat.textContent=`${Math.min(hits,3)}/3`;if(total>=3){clearInterval(timer);liveDone(id,.35+hits*.18)}}}
function liveDone(id,score){const r=E.resolvePerformanceCue(state,id,score);if(!r.ok)return toastMsg(r.reason);save(false);toastMsg(`现场得分 ${r.score}`);render()}
function ending(){const p=state.performance,id=state.ending,text={perfect:['观众沉默三秒后全体起立，旧剧院收到最后一次满场掌声。','地面频道称这是失重年代最完整的谢幕。'],closed:['演出完成了，但关停令没有改变。','观众会记得今晚，剧院将在明晨熄灯。'],rough:['事故接连发生，演员用即兴把故事勉强拉回终点。','评价两极，但没有人提前离场。'],failure:['关键设备在终幕停摆，剧情无法收束。','惋惜的通讯声在轨道上久久不散。']}[id];app.innerHTML=`<div class="menu"><div class="menu-card ending-card"><div class="orbit"></div><div class="big-ending">${E.endingTitle(id)}</div><p>最终评分 ${p.total} ｜ 基础 ${p.base} ｜ 现场 ${p.score}</p><p>${text[0]}</p><p>${text[1]}</p><div class="grid2">${state.members.map(m=>`<div class="member"><b>${m.name}</b><p>${m.route||'路线未定'}｜成长 ${m.xp}｜剧情 ${m.story}/3｜疲劳 ${m.fatigue}</p></div>`).join('')}</div><h3>关键选择</h3><div class="log-list">${p.operations.map(o=>`<div class="log-entry">${o.cue}<br><small>${o.choice} · 决策${o.score} · 操作${o.operation}</small></div>`).join('')}${p.failureReasons?.length?`<div class="log-entry danger">短板：${p.failureReasons.join('、')}</div>`:''}</div><div class="menu-actions"><button class="primary" onclick="E.clearSave();location.reload()">重新录制</button><button onclick="state=null;render()">返回主菜单</button></div></div></div>`}
render();
