import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from './engine.js';
test('member stats grow and fatigue changes',()=>{const s=E.createInitialState(),before=E.getMember(s,'lin').acting,r=E.completeTraining(s,'lines',['lin'],.95,()=>0);assert.equal(r.ok,true);assert.ok(E.getMember(s,'lin').acting>before);assert.ok(E.getMember(s,'lin').fatigue>14);});
test('fatigue stress trust and relationships change',()=>{const s=E.createInitialState(),before=E.getRelationship(s,'lin','qing');E.completeTraining(s,'ensemble',['lin','qing'],.2,()=>0);assert.ok(E.getRelationship(s,'lin','qing')<before);assert.ok(E.getMember(s,'lin').stress>22);assert.ok(E.getMember(s,'lin').trust<56);});
test('resources gate and are consumed by training',()=>{const s=E.createInitialState();s.resources.energy=1;assert.equal(E.canTrain(s,'lines',['lin']).ok,false);s.resources.energy=68;const e=s.resources.energy;E.completeTraining(s,'lines',['lin'],.8,()=>0);assert.equal(s.resources.energy,e-7);});
test('failed technical training damages equipment',()=>{const s=E.createInitialState();s.locations.lighting.unlocked=true;const b=s.devices.lights.status;E.completeTraining(s,'lighting',['mika'],.1,()=>0);assert.ok(s.devices.lights.status<b);assert.ok(s.log.some(x=>x.kind==='danger'));});
test('map locks and device state are linked',()=>{const s=E.createInitialState();s.devices.power.status=20;E.adjustDevice(s,'power',0);assert.equal(s.locations.lighting.closed,true);s.devices.power.status=70;E.adjustDevice(s,'power',0);E.unlockChecks(s);assert.equal(s.locations.lighting.unlocked,true);});
test('all ten events have distinct usable branches',()=>{for(const id of Object.keys(E.EVENT_DEFS)){const a=E.createInitialState(),b=E.createInitialState();for(const x of [a,b]){x.resources.credits=300;x.resources.parts=5;x.resources.energy=100;x.resources.expectation=80;x.members.forEach(m=>Object.assign(m,{acting:90,reaction:90,tech:90,trust:90}));Object.keys(x.relationships).forEach(k=>x.relationships[k]=90);}a.activeEvent={id,...E.EVENT_DEFS[id]};b.activeEvent={id,...E.EVENT_DEFS[id]};assert.ok(E.EVENT_DEFS[id].options.length>=2);E.resolveEvent(a,E.EVENT_DEFS[id].options[0].id);const second=[...E.EVENT_DEFS[id].options].reverse().find(o=>!o.need||o.need(b));assert.ok(second);E.resolveEvent(b,second.id);const snap=x=>JSON.stringify({r:x.resources,f:x.flags,d:x.devices,m:x.members,c:x.eventLog.at(-1)?.choice});assert.notEqual(snap(a),snap(b));}});
function strongState(){const s=E.createInitialState();s.members.forEach(m=>Object.assign(m,{acting:95,rhythm:90,focus:90,stamina:85,tech:92,reaction:92,trust:95,fatigue:15,stress:12}));Object.keys(s.relationships).forEach(k=>s.relationships[k]=90);Object.values(s.devices).forEach(d=>d.status=95);Object.assign(s.resources,{energy:100,parts:9,credits:300,rehearsalTime:20,props:100,expectation:95});s.flags.rewrite='accept';return s;}
function runEnding(s,scores){E.startPerformance(s);E.confirmPerformanceSetup(s,{lead:'lin',understudy:'qing',engineer:'gu',firstLight:'mika',backup:'battery'});for(const score of scores){const cue=E.performanceCueInfo(s),option=cue.options.find(o=>!o.need||o.need(s,s.performance))||cue.options[0];E.resolvePerformanceCue(s,option.id,score);}return s.ending;}
test('perfect ending is reachable',()=>assert.equal(runEnding(strongState(),[1,1,1,1]),'perfect'));
test('closed ending is reachable',()=>{const s=strongState();s.members.forEach(m=>Object.assign(m,{acting:62,rhythm:62,focus:62,tech:62,reaction:62,trust:62,fatigue:45}));Object.values(s.devices).forEach(d=>d.status=55);Object.keys(s.relationships).forEach(k=>s.relationships[k]=45);s.resources.expectation=40;E.startPerformance(s);E.confirmPerformanceSetup(s,{lead:'gu',understudy:'lin',engineer:'mika',firstLight:'qing',backup:'battery'});for(const id of ['spot','risk','repeat','battery'])E.resolvePerformanceCue(s,id,.35);assert.equal(s.ending,'closed');});
test('rough ending is reachable',()=>{const s=strongState();s.members.forEach(m=>Object.assign(m,{acting:45,rhythm:45,focus:45,tech:45,reaction:45,trust:45,fatigue:78}));Object.values(s.devices).forEach(d=>d.status=35);Object.keys(s.relationships).forEach(k=>s.relationships[k]=35);s.resources.expectation=30;assert.equal(runEnding(s,[.35,.35,.35,.35]),'rough');});
test('failure ending is reachable',()=>{const s=E.createInitialState();s.members.forEach(m=>Object.assign(m,{acting:20,rhythm:20,focus:20,stamina:20,tech:20,reaction:20,trust:20,fatigue:85,stress:85}));Object.values(s.devices).forEach(d=>d.status=15);Object.keys(s.relationships).forEach(k=>s.relationships[k]=20);Object.assign(s.resources,{expectation:15,parts:0});E.startPerformance(s);E.confirmPerformanceSetup(s,{lead:'lin',understudy:'qing',engineer:'gu',firstLight:'mika',backup:'none'});for(let i=0;i<4;i++){const cue=E.performanceCueInfo(s);E.resolvePerformanceCue(s,cue.options[cue.options.length-1].id,.2);}assert.equal(s.ending,'failure');});
function prepState(){const s=E.createInitialState();E.startPerformance(s);return s;}
const goodSetup={lead:'lin',understudy:'qing',engineer:'gu',firstLight:'mika',backup:'battery'};
function assertRejected(setup){const s=prepState(),before=E.clone(s);const r=E.confirmPerformanceSetup(s,setup);assert.equal(r.ok,false);assert.ok(typeof r.reason==='string'&&r.reason.length>0);assert.deepEqual(s,before);assert.equal(s.performance.stage,'prep');assert.equal(s.performance.setup,null);assert.equal(s.performance.score,0);}
test('setup rejects duplicate members across roles',()=>{for(const dup of[{lead:'lin',understudy:'lin'},{lead:'gu',engineer:'gu'},{understudy:'mika',firstLight:'mika'},{lead:'qing',understudy:'qing',engineer:'qing',firstLight:'qing'}])assertRejected({...goodSetup,...dup});});
test('setup rejects unknown member ids',()=>{for(const role of['lead','understudy','engineer','firstLight'])assertRejected({...goodSetup,[role]:'ghost'});});
test('setup rejects missing empty and non-string fields',()=>{for(const role of['lead','understudy','engineer','firstLight']){const bad={...goodSetup};delete bad[role];assertRejected(bad);for(const v of['',null,undefined,0,42,{},[],['lin']])assertRejected({...goodSetup,[role]:v});}});
test('setup rejects invalid backup plans',()=>{for(const v of['solar','BATTERY','',null,undefined,1,{},[]])assertRejected({...goodSetup,backup:v});const bad={...goodSetup};delete bad.backup;assertRejected(bad);});
test('setup rejects non-object input',()=>{for(const v of[null,undefined,'lin',42,['lin','qing','gu','mika','battery']])assertRejected(v);});
test('valid setup locks and synergy matches real pair relationships',()=>{const s=prepState();s.relationships['lin-qing']=55;s.relationships['gu-mika']=50;const before=E.clone(s);const r=E.confirmPerformanceSetup(s,goodSetup);assert.equal(r.ok,true);assert.equal(r.synergy,14);assert.equal(s.performance.score,14);assert.equal(s.performance.stage,'cue');assert.equal(s.performance.cue,1);assert.deepEqual(s.performance.setup,goodSetup);assert.notEqual(s.performance.setup,goodSetup);assert.ok(!Object.keys(s.relationships).some(k=>{const[a,b]=k.split('-');return a===b;}));const after=E.clone(s);assert.equal(after.performance.score-before.performance.score,14);assert.equal(after.log.length,before.log.length+1);});
test('synergy is zero when relationships are below thresholds',()=>{const s=prepState();s.relationships['lin-qing']=54;s.relationships['gu-mika']=49;const r=E.confirmPerformanceSetup(s,goodSetup);assert.equal(r.ok,true);assert.equal(r.synergy,0);assert.equal(s.performance.score,0);});
test('resubmitting a locked setup fails without double scoring',()=>{const s=prepState();s.relationships['lin-qing']=90;s.relationships['gu-mika']=90;assert.equal(E.confirmPerformanceSetup(s,goodSetup).synergy,14);const before=E.clone(s);const r=E.confirmPerformanceSetup(s,goodSetup);assert.equal(r.ok,false);assert.deepEqual(s,before);assert.equal(s.performance.score,14);});
test('validated setup drives all four cues and settlement',()=>{const s=strongState();E.startPerformance(s);const r=E.confirmPerformanceSetup(s,goodSetup);assert.equal(r.ok,true);assert.equal(r.synergy,14);const seen=[];for(const id of['light','brake','improv','battery']){const cue=E.performanceCueInfo(s);seen.push(cue.id);const res=E.resolvePerformanceCue(s,id,1);assert.equal(res.ok,true,`cue ${cue.id} option ${id} rejected`);}assert.deepEqual(seen,['opening','lift','delay','ending']);assert.equal(s.performance.stage,'result');assert.equal(s.ended,true);assert.equal(s.ending,'perfect');assert.equal(s.performance.operations.length,4);assert.equal(s.performance.total,E.clamp(s.performance.base+s.performance.score,0,110));const improv=s.performance.operations[2];assert.ok(improv.score>20,'understudy relationship from locked setup feeds the improv cue');});
