const STAT_KEYS = ['acting','rhythm','focus','stamina','tech','reaction','trust'];
export const clamp=(v,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(v)));
export function makeRng(seed=1){let t=seed>>>0;return()=>{t+=0x6D2B79F5;let r=Math.imul(t^(t>>>15),t|1);r^=r+Math.imul(r^(r>>>7),r|61);return((r^(r>>>14))>>>0)/4294967296;};}
export const clone=v=>JSON.parse(JSON.stringify(v));
export const getMember=(s,id)=>s.members.find(m=>m.id===id);
export const relKey=(a,b)=>[a,b].sort().join('-');
export const getRelationship=(s,a,b)=>s.relationships[relKey(a,b)]??50;
export function setRelationship(s,a,b,v){s.relationships[relKey(a,b)]=clamp(v);}
export function addRelationship(s,a,b,v){setRelationship(s,a,b,getRelationship(s,a,b)+v);}
export function addLog(s,title,detail='',kind='info'){s.log.unshift({day:s.day,title,detail,kind});s.log=s.log.slice(0,90);}
export function createInitialState(){return{version:1,day:1,phase:'morning',location:'stage',actions:4,rngSeed:Date.now()%2147483647,
resources:{energy:68,parts:8,credits:120,rehearsalTime:4,props:72,expectation:42},
members:[
{id:'lin',name:'林杳',role:'主演',trait:'完美主义者',goal:'完成母亲未竟的独白',xp:0,acting:72,rhythm:54,focus:55,stamina:61,tech:25,reaction:48,trust:56,fatigue:14,stress:22,injured:false,route:null,assignment:'待命',story:0},
{id:'gu',name:'顾壑',role:'舞台工程师',trait:'沉默可靠',goal:'让升降台最后一次安全运转',xp:0,acting:24,rhythm:42,focus:63,stamina:72,tech:82,reaction:55,trust:50,fatigue:18,stress:18,injured:false,route:null,assignment:'待命',story:0},
{id:'mika',name:'米卡',role:'灯光师',trait:'直觉敏锐',goal:'用光找回第一幕',xp:0,acting:32,rhythm:70,focus:67,stamina:52,tech:61,reaction:64,trust:48,fatigue:16,stress:26,injured:false,route:null,assignment:'待命',story:0},
{id:'qing',name:'晴文',role:'替补演员',trait:'临场大胆',goal:'获得真正属于自己的出场',xp:0,acting:55,rhythm:60,focus:43,stamina:56,tech:31,reaction:76,trust:45,fatigue:10,stress:19,injured:false,route:null,assignment:'待命',story:0}],
relationships:{'lin-gu':42,'lin-mika':55,'lin-qing':38,'gu-mika':47,'gu-qing':44,'mika-qing':51},
devices:{power:{name:'主供电母线',status:58,damaged:false},lights:{name:'轨道灯光阵列',status:62,damaged:false},lift:{name:'零重力升降台',status:46,damaged:false},audio:{name:'回声音响环',status:65,damaged:false},life:{name:'生命维持系统',status:76,damaged:false},props:{name:'磁力道具柜',status:70,damaged:false},console:{name:'应急控制台',status:52,damaged:false}},
locations:{stage:{name:'主舞台',unlocked:true,closed:false},backstage:{name:'后台',unlocked:true,closed:false},rehearsal:{name:'排练室',unlocked:true,closed:false},lighting:{name:'灯光室',unlocked:false,closed:false},repair:{name:'维修舱',unlocked:false,closed:false},storage:{name:'储藏间',unlocked:true,closed:false},audience:{name:'观众席',unlocked:false,closed:false}},
log:[],eventLog:[],flags:{introSeen:false,eventDoneToday:false,sponsorLeft:false,rewrite:false,earlyAudience:false,signalStorm:0,overheat:0,pendingAbsence:false,nightAccident:false},activeEvent:null,performance:null,ending:null,ended:false,
stats:{workCount:0,trainingCount:0,failures:0,rehearsals:0,repairs:0,keyChoices:[]}};}
export function adjustMember(m,c){for(const[k,v]of Object.entries(c)){if(k==='injured')m.injured=!!v;else if(STAT_KEYS.includes(k)||k==='fatigue'||k==='stress')m[k]=clamp(m[k]+v);else if(k==='xp')m.xp+=v;}}
export function adjustResources(s,c){for(const[k,v]of Object.entries(c))s.resources[k]=clamp(s.resources[k]+v,0,k==='credits'?999:200);}
export function adjustDevice(s,id,v){const d=s.devices[id];if(!d)return;d.status=clamp(d.status+v);d.damaged=d.status<25;if(id==='power'&&d.status<30){s.locations.lighting.closed=true;s.flags.signalStorm=Math.max(s.flags.signalStorm,1);}if(id==='life'&&d.status>=35)s.locations.stage.closed=false;}
export function unlockChecks(s){s.locations.lighting.unlocked||=s.devices.power.status>=35||getMember(s,'mika').story>=1;s.locations.repair.unlocked||=s.day>=2||getMember(s,'gu').story>=1;s.locations.audience.unlocked||=s.day>=3||s.resources.expectation>=55;}
export function moveLocation(s,id){const l=s.locations[id];if(!l)return{ok:false,reason:'区域不存在'};if(!l.unlocked)return{ok:false,reason:'区域尚未解锁'};if(l.closed)return{ok:false,reason:'区域因安全事故关闭'};s.location=id;return{ok:true};}
export const TRAINING_INFO={lines:{name:'台词训练',place:'rehearsal',primary:'acting',secondary:'focus',energy:7,time:1},rhythm:{name:'节奏训练',place:'rehearsal',primary:'rhythm',secondary:'reaction',energy:7,time:1},lighting:{name:'灯光操作',place:'lighting',primary:'tech',secondary:'focus',energy:8,time:1},repair:{name:'舞台维修',place:'repair',primary:'tech',secondary:'focus',energy:9,time:1},reaction:{name:'临场反应',place:'stage',primary:'reaction',secondary:'stamina',energy:8,time:1},ensemble:{name:'团队排练',place:'stage',primary:'trust',secondary:'rhythm',energy:9,time:1}};
export function canTrain(s,type,ids=[]){const i=TRAINING_INFO[type];if(!i)return{ok:false,reason:'未知训练'};if(s.day>=10)return{ok:false,reason:'今天必须进入最终演出'};if(s.phase!=='morning')return{ok:false,reason:'只能在晨间安排训练'};if(s.actions<1)return{ok:false,reason:'今日行动次数已用完'};if(s.resources.rehearsalTime<i.time)return{ok:false,reason:'排练时间不足'};if(s.resources.energy<i.energy)return{ok:false,reason:'能源不足，训练取消'};const l=s.locations[i.place];if(!l.unlocked)return{ok:false,reason:`${l.name}尚未解锁`};if(l.closed)return{ok:false,reason:`${l.name}暂时关闭`};const ms=ids.map(id=>getMember(s,id));if(!ms.length||ms.some(m=>!m))return{ok:false,reason:'请选择参与成员'};if(ms.some(m=>m.injured))return{ok:false,reason:'受伤成员不能参加高强度训练'};if(type==='ensemble'&&ms.length<2)return{ok:false,reason:'团队排练至少需要两人'};return{ok:true,info:i};}
function developRoute(m,type){const map={lin:{lines:'star',ensemble:'director'},gu:{repair:'engineer',reaction:'safety'},mika:{lighting:'painter',rhythm:'conductor'},qing:{reaction:'improviser',ensemble:'leader'}};const r=map[m.id]?.[type];if(!r)return;if(!m.route)m.route=r;if(m.route===r)adjustMember(m,{xp:4,trust:1});}
export function completeTraining(s,type,ids,score=.7,rng=Math.random){const check=canTrain(s,type,ids);if(!check.ok)return check;const i=check.info;s.actions--;s.resources.energy-=i.energy;s.resources.rehearsalTime-=i.time;s.stats.trainingCount++;const ms=ids.map(id=>getMember(s,id));const success=score>=.48;const overload=ms.some(m=>m.fatigue>72||m.stress>75);
if(success){ms.forEach((m,idx)=>{const apt=(m[i.primary]+m[i.secondary])/200;const gain=Math.round((7+score*15)*(.65+apt)*(idx?.82:1));adjustMember(m,{xp:gain,[i.primary]:gain,[i.secondary]:Math.round(gain*.55),fatigue:8+score*3,stress:overload?8:3});m.assignment=i.name;developRoute(m,type);});for(let a=0;a<ms.length;a++)for(let b=a+1;b<ms.length;b++)addRelationship(s,ms[a].id,ms[b].id,type==='ensemble'?5:2);
if(type==='repair')repairAction(s,ms[0].id,Math.round(4+score*9),false);if(type==='lighting'){adjustDevice(s,'lights',Math.round(5+score*10));s.resources.expectation+=2;}if(type==='ensemble'){s.resources.expectation+=Math.round(4+score*6);s.stats.rehearsals++;}if(['lines','reaction'].includes(type))s.resources.props=clamp(s.resources.props+Math.round(score*4));addLog(s,`${i.name}完成`,`${ms.map(m=>m.name).join('、')}获得 ${Math.round(score*100)} 分。`,'success');}
else{s.stats.failures++;ms.forEach(m=>{adjustMember(m,{[i.secondary]:1,fatigue:13,stress:12,trust:-4});m.assignment=`${i.name}失误`;});for(let a=0;a<ms.length;a++)for(let b=a+1;b<ms.length;b++)addRelationship(s,ms[a].id,ms[b].id,-5);if(type==='repair'||type==='lighting')adjustDevice(s,type==='repair'?(rng()>.5?'lift':'power'):'lights',-9);if(overload){const v=ms[Math.floor(rng()*ms.length)];v.injured=rng()>.45;adjustMember(v,{stress:8});s.flags.nightAccident=true;addLog(s,'高强度任务失控',v.injured?`${v.name}受轻伤，需要休养。`:`${v.name}与队友发生争执。`,'danger');}addLog(s,`${i.name}失败`,'能源已消耗，设备和信任受到影响。','danger');}
unlockChecks(s);checkPersonalStories(s);return{ok:true,success,score};}
export function repairAction(s,id,amount=10,spend=true){const m=getMember(s,id);if(!m)return{ok:false,reason:'请选择工程师'};if(s.phase!=='morning')return{ok:false,reason:'现在不能维修'};if(s.actions<1)return{ok:false,reason:'行动次数不足'};if(spend&&(s.resources.energy<5||s.resources.parts<1))return{ok:false,reason:'维修需要 5 能源和 1 零件'};s.actions--;if(spend){s.resources.energy-=5;s.resources.parts--;}const targets=Object.keys(s.devices).filter(d=>s.devices[d].status<85).sort((a,b)=>s.devices[a].status-s.devices[b].status);const target=targets[0];const gain=Math.round(amount*(.55+m.tech/100)+(m.route==='engineer'?5:0));adjustDevice(s,target,gain);adjustMember(m,{tech:3,focus:2,fatigue:10,stress:2,xp:gain});m.assignment='设备维修';s.stats.repairs++;if(target==='power')s.locations.lighting.closed=s.devices.power.status<30;addLog(s,'设备维修完成',`${m.name}修复了${s.devices[target].name}，完整度 +${gain}。`,'success');unlockChecks(s);checkPersonalStories(s);return{ok:true,target,gain};}
export function restMember(s,id){const m=getMember(s,id);if(!m)return{ok:false,reason:'请选择成员'};if(s.actions<1)return{ok:false,reason:'行动次数不足'};s.actions--;const heal=m.injured&&(m.fatigue<35||m.stress<35);adjustMember(m,{fatigue:-24,stress:-18,trust:2,xp:m.injured?0:2});if(heal){m.injured=false;addLog(s,'伤情稳定',`${m.name}经过休息恢复行动。`,'success');}m.assignment='低强度休息';addLog(s,'安排休息',`${m.name}恢复疲劳和压力，但今天训练进度放缓。`);return{ok:true};}
export function workJob(s,id,kind){const m=getMember(s,id);const jobs={signal:{name:'外部信号检修',energy:6,fatigue:16,reward:{credits:34,energy:4},stat:'tech'},cargo:{name:'货舱搬运',energy:4,fatigue:18,reward:{parts:3,credits:10},stat:'stamina'},promo:{name:'轨道宣传演出',energy:7,fatigue:14,reward:{credits:22,expectation:12},stat:'acting'}};const j=jobs[kind];if(!j)return{ok:false,reason:'未知工作'};if(s.actions<1)return{ok:false,reason:'行动次数不足'};if(s.resources.energy<j.energy)return{ok:false,reason:'能源不足，工作取消'};if(m.injured)return{ok:false,reason:'受伤成员不能工作'};s.actions--;s.resources.energy-=j.energy;const good=(m[j.stat]+m.reaction)/2+(m.fatigue>70?-25:0)>55;if(good){adjustResources(s,j.reward);adjustMember(m,{[j.stat]:3,xp:8,fatigue:j.fatigue,stress:3});m.assignment=j.name;s.stats.workCount++;addLog(s,`${j.name}成功`,`${m.name}带回了资源。`,'success');}else{adjustResources(s,{credits:6});adjustMember(m,{fatigue:j.fatigue+8,stress:12,trust:-3});m.assignment=`${j.name}受挫`;s.resources.expectation=clamp(s.resources.expectation-3);addLog(s,`${j.name}出岔`,`报酬减少，成员状态下降。`,'danger');}return{ok:true,good};}
export function buyItem(s,item){const shop={battery:{cost:28,change:{energy:18}},parts:{cost:22,change:{parts:2}},props:{cost:35,change:{props:16,expectation:4}},ration:{cost:18,change:{},restAll:8}};const x=shop[item];if(!x)return{ok:false,reason:'未知物资'};if(s.resources.credits<x.cost)return{ok:false,reason:'资金不足'};s.resources.credits-=x.cost;adjustResources(s,x.change);if(x.restAll)s.members.forEach(m=>adjustMember(m,{fatigue:-x.restAll,stress:-3}));addLog(s,'储藏间采购',`购入${item==='battery'?'能源电池':item==='parts'?'维修零件':item==='props'?'磁力道具':'营养餐包'}。`);return{ok:true};}
export function checkPersonalStories(s){const rules=[
{id:'lin',n:1,test:m=>m.acting>=82,title:'林杳：未寄出的独白',text:'她承认自己害怕重演母亲失败的那场戏。',effects:{trust:6,stress:-6}},
{id:'lin',n:2,test:(m,s)=>m.story>=1&&getRelationship(s,'lin','qing')>=55,title:'林杳：把第二幕交给新人',text:'林杳决定让晴文接管一段即兴段落。',effects:{reaction:4,trust:8}},
{id:'lin',n:3,test:m=>m.story>=2&&m.route==='star'&&m.acting>=92,title:'林杳：失重独白',text:'她在漂浮中找到属于自己的节奏。',effects:{acting:5,focus:5,trust:8}},
{id:'gu',n:1,test:m=>m.tech>=88||s.stats.repairs>=2,title:'顾壑：升降台的旧编号',text:'他保留着剧院首演时的安全手册。',effects:{tech:4,trust:5}},
{id:'gu',n:2,test:(m,s)=>m.story>=1&&getRelationship(s,'gu','mika')>=58,title:'顾壑：给光留一条轨道',text:'工程师和灯光师重设了机械与灯光同步点。',effects:{focus:5,reaction:3}},
{id:'gu',n:3,test:m=>m.story>=2&&m.route==='engineer'&&s.devices.lift.status>=80,title:'顾壑：最后的安全锁',text:'升降台完成改装，可以在断电时手动回收。',effects:{tech:5,trust:8}},
{id:'mika',n:1,test:m=>m.tech>=70||m.rhythm>=78,title:'米卡：第一束光',text:'她调出了档案里失传的蓝金色开场光。',effects:{rhythm:4,trust:5}},
{id:'mika',n:2,test:(m,s)=>m.story>=1&&getRelationship(s,'mika','lin')>=65,title:'米卡：光不会抢台词',text:'米卡学会用光托住林杳的停顿。',effects:{focus:5,acting:2}},
{id:'mika',n:3,test:m=>m.story>=2&&m.route==='painter'&&s.devices.lights.status>=85,title:'米卡：终幕光谱',text:'她完成三套现场光谱，足以应对突发停电。',effects:{tech:5,reaction:5}},
{id:'qing',n:1,test:m=>m.reaction>=84,title:'晴文：候补的第一千次准备',text:'她证明自己不是替补，而是现场变数的答案。',effects:{reaction:4,trust:6}},
{id:'qing',n:2,test:(m,s)=>m.story>=1&&getRelationship(s,'qing','lin')>=58,title:'晴文：借来的勇气',text:'林杳把一枚旧胸针交给晴文。',effects:{acting:5,trust:5}},
{id:'qing',n:3,test:m=>m.story>=2&&m.route==='improviser'&&m.reaction>=92,title:'晴文：没有剧本的救场',text:'她准备好在终幕带全队越过任何事故。',effects:{reaction:5,focus:5,trust:8}}];
for(const r of rules){const m=getMember(s,r.id);if(m.story===r.n-1&&r.test(m,s)){m.story=r.n;Object.entries(r.effects).forEach(([k,v])=>adjustMember(m,{[k]:v}));s.eventLog.push({day:s.day,type:'story',title:r.title,detail:r.text});addLog(s,r.title,r.text,'story');}}
}
export const EVENT_DEFS={
blackout:{title:'舞台断电',text:'母线在无重力走廊里闪出火花，灯光室即将离线。',options:[
{id:'manual',label:'手动切换应急母线',need:s=>s.devices.console.status>=35&&s.resources.parts>=1,run:s=>{s.resources.parts--;adjustDevice(s,'power',18);adjustDevice(s,'console',-8);getMember(s,'gu').fatigue=clamp(getMember(s,'gu').fatigue+14);return'顾壑稳住母线，灯光室保持开放。';}},
{id:'cut',label:'削减非必要照明',run:s=>{adjustResources(s,{energy:14,expectation:-9});s.devices.lights.status=clamp(s.devices.lights.status-8);return'能源保住了，但观众期待下降。';}}]},
fight:{title:'成员争执',text:'林杳认为晴文擅自改词，晴文则觉得自己总被当作备份。',options:[
{id:'mediate',label:'让米卡从中调解',need:s=>getRelationship(s,'lin','qing')>=35&&getMember(s,'mika').trust>=50,run:s=>{addRelationship(s,'lin','qing',12);adjustMember(getMember(s,'lin'),{stress:-8});adjustMember(getMember(s,'qing'),{trust:7});return'两人决定把即兴段落明确分工。';}},
{id:'side',label:'维持原剧本',run:s=>{addRelationship(s,'lin','qing',-10);adjustMember(getMember(s,'qing'),{stress:14,trust:-6});adjustResources(s,{props:5});return'纪律恢复，但晴文的积极性受挫。';}}]},
props:{title:'道具损坏',text:'磁扣失效，关键月面仪在后台漂浮散开。',options:[
{id:'repair',label:'连夜重制道具',need:s=>s.resources.parts>=2&&s.resources.energy>=6,run:s=>{s.resources.parts-=2;s.resources.energy-=6;s.resources.props=clamp(s.resources.props+18);s.members.forEach(m=>adjustMember(m,{fatigue:6}));return'月面仪更坚固，道具完整度提升。';}},
{id:'mime',label:'改成无实物表演',need:s=>getMember(s,'lin').acting>=75,run:s=>{adjustMember(getMember(s,'lin'),{acting:4,stress:8});s.resources.expectation+=6;s.resources.props=clamp(s.resources.props-10);return'缺憾变成独特的表演风格。';}}]},
audience:{title:'观众提前入场',text:'接驳船提早抵达，观众已经透过气窗看向舞台。',options:[
{id:'preview',label:'安排米卡展示灯光',need:s=>s.locations.lighting.unlocked&&s.devices.lights.status>=50,run:s=>{s.resources.energy-=7;adjustResources(s,{expectation:16});adjustMember(getMember(s,'mika'),{fatigue:10,trust:5});s.flags.earlyAudience=true;return'预演光秀让期待值大涨。';}},
{id:'delay',label:'请乘务组延迟入场',run:s=>{adjustResources(s,{credits:-15,expectation:-4});return'支付协调费，现场没有穿帮。';}}]},
signal:{title:'外部信号干扰',text:'广告卫星反复切断控制台与灯轨的握手信号。',options:[
{id:'shield',label:'制作屏蔽线圈',need:s=>getMember(s,'gu').tech>=75&&s.resources.parts>=1,run:s=>{s.resources.parts--;adjustDevice(s,'console',15);adjustMember(getMember(s,'gu'),{focus:4,fatigue:10});s.flags.signalStorm=0;return'屏蔽线圈生效，终幕操作更稳定。';}},
{id:'ignore',label:'忽略干扰继续排练',run:s=>{s.flags.signalStorm=2;adjustDevice(s,'lights',-10);adjustResources(s,{rehearsalTime:1});return'干扰持续，灯光阵列留下隐患。';}}]},
accident:{title:'排练事故',text:'升降台轻微抖动，晴文在空中失去平衡。',options:[
{id:'catch',label:'让顾壑手动制动',need:s=>getMember(s,'gu').reaction>=50,run:s=>{adjustDevice(s,'lift',-6);adjustMember(getMember(s,'gu'),{fatigue:12,reaction:3,trust:6});return'制动成功，队伍更信任顾壑。';}},
{id:'stop',label:'立刻停止排练',run:s=>{s.resources.rehearsalTime=clamp(s.resources.rehearsalTime-2);adjustMember(getMember(s,'qing'),{stress:-8});s.flags.nightAccident=true;return'安全优先，但损失两个排练小时。';}}]},
absence:{title:'临时演员缺席',text:'外借的轨道舞者因船班取消无法到场。',options:[
{id:'qing',label:'让晴文顶替',need:s=>getMember(s,'qing').reaction>=70,run:s=>{adjustMember(getMember(s,'qing'),{acting:5,trust:8,stress:8});addRelationship(s,'lin','qing',6);s.flags.pendingAbsence=false;return'晴文获得真正的核心段落。';}},
{id:'robot',label:'用机械臂替代',need:s=>s.resources.credits>=25,run:s=>{s.resources.credits-=25;adjustDevice(s,'lift',-8);s.resources.expectation-=3;return'机械臂能完成动作，却缺少人的温度。';}}]},
overheat:{title:'设备过热',text:'灯轨散热器发出红色警报，继续使用可能烧毁。',options:[
{id:'cool',label:'关闭设备降温',run:s=>{s.resources.energy-=4;s.actions=Math.max(0,s.actions-1);adjustDevice(s,'lights',12);s.flags.overheat=0;return'设备恢复，但占用一次行动。';}},
{id:'push',label:'冒险继续运行',need:s=>getMember(s,'mika').tech>=65,run:s=>{adjustDevice(s,'lights',-18);adjustResources(s,{expectation:8});s.flags.overheat=2;return'当天效果惊艳，但灯轨将在终幕出问题。';}}]},
sponsor:{title:'赞助方撤资',text:'投资方认为剧院关停已成定局，要求提前终止赞助。',options:[
{id:'convince',label:'播放排练片段谈判',need:s=>s.resources.expectation>=55,run:s=>{adjustResources(s,{credits:45,expectation:8});getMember(s,'lin').trust=clamp(getMember(s,'lin').trust+5);return'观众期待说服了赞助方。';}},
{id:'crowd',label:'发起观众众筹',run:s=>{s.resources.credits+=22;s.flags.sponsorLeft=true;s.resources.energy=clamp(s.resources.energy-8);return'众筹不多，但剧团保住自主权。';}}]},
rewrite:{title:'剧本修改',text:'编剧从地面发来新结尾，要求终幕减少特效、强化人物和解。',options:[
{id:'accept',label:'采纳新结尾',need:s=>getMember(s,'lin').acting>=70&&getRelationship(s,'lin','qing')>=45,run:s=>{s.flags.rewrite='accept';adjustMember(getMember(s,'lin'),{acting:4});adjustMember(getMember(s,'qing'),{trust:7});addRelationship(s,'lin','qing',8);return'新结尾给演员更多现场发挥空间。';}},
{id:'keep',label:'保留原特效剧本',run:s=>{s.flags.rewrite='keep';s.resources.expectation+=7;s.resources.parts=clamp(s.resources.parts-1);return'场面更华丽，但终幕更依赖设备。';}}]}
};
export function maybeTriggerEvent(s,rng=Math.random){if(s.flags.eventDoneToday||s.day>=10)return null;const forced={1:'blackout',2:'fight',3:'props',4:'overheat',5:'sponsor',6:'signal',7:'accident',8:'absence',9:'rewrite'}[s.day];let id=forced;if(!forced||s.eventLog.some(e=>e.key===id))id=Object.keys(EVENT_DEFS)[Math.floor(rng()*Object.keys(EVENT_DEFS).length)];const def=EVENT_DEFS[id];s.activeEvent={id,...def};s.phase='event';return s.activeEvent;}
export function resolveEvent(s,optionId){if(!s.activeEvent)return{ok:false,reason:'当前没有突发事件'};const option=s.activeEvent.options.find(o=>o.id===optionId);if(!option)return{ok:false,reason:'选项不存在'};if(option.need&&!option.need(s))return{ok:false,reason:'条件不足，无法选择'};const detail=option.run(s);s.flags.eventDoneToday=true;s.eventLog.push({day:s.day,type:'event',key:s.activeEvent.id,title:s.activeEvent.title,choice:option.label,detail});addLog(s,s.activeEvent.title,`${option.label}：${detail}`,'event');s.activeEvent=null;s.phase='night';checkPersonalStories(s);return{ok:true,detail};}
export function endDay(s){if(s.day>=10)return startPerformance(s);s.phase='night';let injuries=s.members.filter(m=>m.injured).length;s.members.forEach(m=>{if(m.assignment==='低强度休息'){adjustMember(m,{fatigue:-8,stress:-5});}else{adjustMember(m,{fatigue:s.flags.signalStorm?4:2,stress:s.flags.overheat?3:1});}if(m.fatigue>85&&!m.injured&&Math.random()>.55){m.injured=true;injuries++;addLog(s,'累积疲劳受伤',`${m.name}因连续高压安排受轻伤。`,'danger');}m.assignment='待命';});
Object.entries(s.devices).forEach(([id,d])=>{d.status=clamp(d.status-(id==='life'?1:id==='power'?4:3));d.damaged=d.status<25;});if(s.devices.power.status<30)s.locations.lighting.closed=true;if(s.flags.signalStorm>0)s.flags.signalStorm--;if(s.flags.overheat>0)s.flags.overheat--;
adjustResources(s,{energy:18,parts:s.day%3===0?1:0,rehearsalTime:3,expectation:s.stats.rehearsals?1:-2});s.day++;s.actions=4;s.phase='morning';s.flags.eventDoneToday=false;unlockChecks(s);addLog(s,`第 ${s.day} 天晨间安排`,'能源重新配给，剧院继续漂流。','info');if(s.day===10)return startPerformance(s);return{ok:true};}
export function teamLevel(s){const avg=k=>s.members.reduce((a,m)=>a+m[k],0)/4;return{acting:avg('acting'),rhythm:avg('rhythm'),focus:avg('focus'),stamina:avg('stamina'),tech:avg('tech'),reaction:avg('reaction'),trust:avg('trust'),fatigue:avg('fatigue'),stress:avg('stress')};}
export function startPerformance(s){s.day=10;s.phase='performance';s.location='stage';const rels=Object.values(s.relationships);const tl=teamLevel(s);const equipment=Object.values(s.devices).reduce((a,d)=>a+d.status,0)/Object.keys(s.devices).length;s.performance={stage:'prep',cue:0,score:0,operations:[],setup:null,base:Math.round(tl.acting*.18+tl.rhythm*.1+tl.focus*.1+tl.tech*.14+tl.reaction*.14+tl.trust*.16+equipment*.12+s.resources.expectation*.1-(tl.fatigue*.08+tl.stress*.05)+rels.reduce((a,b)=>a+b,0)/rels.length*.03)};addLog(s,'最终演出开始','确认站位、设备、灯光顺序和备用方案。','event');return s.performance;}
export const PERFORMANCE_SLOTS=['lead','understudy','engineer','firstLight'];
export const PERFORMANCE_SLOT_LABELS={lead:'主演',understudy:'替补',engineer:'机械设备',firstLight:'第一灯光'};
export const PERFORMANCE_BACKUPS=['battery','human','none'];
export function validatePerformanceSetup(s,setup){
  if(!setup||typeof setup!=='object'||Array.isArray(setup))return{ok:false,reason:'演出方案必须是对象'};
  for(const k of PERFORMANCE_SLOTS){
    const v=setup[k];
    if(typeof v!=='string'||v.trim()==='')return{ok:false,reason:`方案缺少有效的${PERFORMANCE_SLOT_LABELS[k]}成员 ID`};
    if(!getMember(s,v))return{ok:false,reason:`${PERFORMANCE_SLOT_LABELS[k]} ${v} 不是现有成员`};
  }
  if(typeof setup.backup!=='string'||!PERFORMANCE_BACKUPS.includes(setup.backup))return{ok:false,reason:'备用方案只能是 battery、human 或 none'};
  if(new Set(PERFORMANCE_SLOTS.map(k=>setup[k])).size<PERFORMANCE_SLOTS.length)return{ok:false,reason:'四个岗位必须由四名不同成员承担'};
  return{ok:true,value:Object.fromEntries([...PERFORMANCE_SLOTS.map(k=>[k,setup[k]]),['backup',setup.backup]])};
}
export function performanceSynergy(s,setup){return(getRelationship(s,setup.lead,setup.understudy)>=55?8:0)+(getRelationship(s,setup.engineer,setup.firstLight)>=50?6:0);}
export function confirmPerformanceSetup(s,setup){if(!s.performance||s.performance.stage!=='prep')return{ok:false,reason:'现在不能修改演出方案'};const check=validatePerformanceSetup(s,setup);if(!check.ok)return check;const locked=Object.freeze({...check.value});s.performance.setup=locked;s.performance.stage='cue';s.performance.cue=1;const synergy=performanceSynergy(s,locked);s.performance.score+=synergy;addLog(s,'演出方案锁定',`默契加成为 ${synergy}。`,'success');return{ok:true,synergy};}
export const PERFORMANCE_CUES=[
{id:'opening',title:'第一次变化：开场前灯轨失准',options:[{id:'light',label:'按光谱手动追光',need:(s,c)=>getMember(s,c.setup.firstLight).tech>=60,score:(s,c)=>18+getMember(s,c.setup.firstLight).tech/8},{id:'spot',label:'改用单束应急追光',score:()=>9}]},
{id:'lift',title:'第二次变化：升降台抖动',options:[{id:'brake',label:'手动制动并改走坡道',need:(s,c)=>s.devices.lift.status>=45||getMember(s,c.setup.engineer).route==='engineer',score:(s,c)=>18+getMember(s,c.setup.engineer).reaction/8},{id:'risk',label:'坚持使用升降台',score:s=>s.devices.lift.status<40?-12:6}]},
{id:'delay',title:'第三次变化：直播信号延迟',options:[{id:'improv',label:'让替补无声表演填补',need:(s,c)=>getMember(s,c.setup.understudy).reaction>=75,score:(s,c)=>20+getRelationship(s,c.setup.lead,c.setup.understudy)/5},{id:'repeat',label:'等待信号后重复台词',score:()=>6}]},
{id:'ending',title:'终幕变化：供电跌落',options:[{id:'human',label:'执行新结尾，手举冷光',need:s=>s.flags.rewrite==='accept',score:(s,c)=>12+getMember(s,c.setup.lead).acting/10},{id:'battery',label:'启用备用电池保灯光',need:(s,c)=>c.setup.backup==='battery'&&s.resources.parts>=1,score:s=>8+s.devices.lights.status/10},{id:'abandon',label:'放弃特效直接谢幕',score:()=>4}]}
];
export function performanceCueInfo(s){if(!s.performance||s.performance.stage!=='cue')return null;return PERFORMANCE_CUES[s.performance.cue-1];}
export function resolvePerformanceCue(s,optionId,operationScore=.7){const cue=performanceCueInfo(s);if(!cue)return{ok:false,reason:'当前不是现场操作'};if(operationScore<.15||operationScore>1.2)return{ok:false,reason:'现场操作成绩无效'};const option=cue.options.find(o=>o.id===optionId);if(!option)return{ok:false,reason:'处置方案不存在'};if(option.need&&!option.need(s,s.performance))return{ok:false,reason:'能力、关系或备用方案不足'};let score=Math.round(option.score(s,s.performance)*(.55+operationScore*.55));if(s.flags.signalStorm&&cue.id==='opening')score-=8;if(s.flags.overheat&&cue.id==='opening')score-=10;s.performance.score+=score;s.performance.operations.push({cue:cue.title,choice:option.label,score,operation:Math.round(operationScore*100)});s.performance.cue++;if(s.performance.cue>PERFORMANCE_CUES.length)return finishPerformance(s);return{ok:true,score,cue:PERFORMANCE_CUES[s.performance.cue-1]};}
export function finishPerformance(s){if(!s.performance)return{ok:false,reason:'演出尚未开始'};const total=clamp(s.performance.base+s.performance.score,0,110);s.performance.total=total;s.performance.stage='result';s.ended=true;s.ending=total>=92?'perfect':total>=72?'closed':total>=50?'rough':'failure';const reasons=[];if(teamLevel(s).fatigue>55)reasons.push('成员疲劳过高');if(s.devices.power.status<45)reasons.push('供电系统不可靠');if(s.resources.expectation<45)reasons.push('观众期待不足');if(Object.values(s.relationships).some(v=>v<35))reasons.push('成员信任裂痕');s.performance.failureReasons=reasons;s.eventLog.push({day:10,type:'ending',title:endingTitle(s.ending),detail:`最终评分 ${total}`});addLog(s,endingTitle(s.ending),`最终评分：${total}`,'success');return{ok:true,total,ending:s.ending};}
export function endingTitle(id){return{perfect:'完美谢幕',closed:'演出完成但剧院关闭',rough:'中途失控后勉强结束',failure:'演出失败'}[id]||'未知结局';}
export function saveGame(state){const data=JSON.stringify({...state,savedAt:new Date().toISOString()});localStorage.setItem('zero-g-theater-save',data);return data;}
export function loadGame(){try{return JSON.parse(localStorage.getItem('zero-g-theater-save')||'null');}catch{return null;}}
export function clearSave(){localStorage.removeItem('zero-g-theater-save');}
